### ISSUE TITLE
Seems to systematically loose the connection after some time

### ISSUE THREAD

**Issue by ashmodai6** [Sholofly/ZiggoNext#53] opened 2020-12-04 13:58 UTC
Hi
First fantastic piece of work. Thanks a lot about this.
I do have an issue with this component that seems to "loose" the connection after some times on a systematic manner. I mean if I don't restart HA the component will stop working (and not display correctly my box status) after 2-3d. 
Is there a way to "ping" the box to be sure the connection is still active and reinitiate it otherwise ? 
Thanks!

**Comment by caro7372** [comment] 2020-12-06 05:36
Yes, I have that same issue too. I recognize this when the screenshot is gone.
Hope there is a soluties.

For the rest, I really like this. Was one of the first I had in HA dashboard.

Regards,

Robert

**Comment by Sholofly** [comment] 2020-12-06 19:43
Do you guys play radio stations?

**Comment by caro7372** [comment] 2020-12-06 19:47
Hi, do you mean radiostations on the ziggo mediabox? No, I’m not. I change my mediaplayer integration with Sonos to Spotify.

Regards,

Robert

**Comment by ashmodai6** [comment] 2020-12-08 12:51
Hi Rudolf, neither do I. Only TV and recordings ... Never any radiostations

**Comment by Polderdijk** [comment] 2020-12-11 22:23
I found a reason when the component loose (a part of the) connection. 

When playing from DVR and turning of the Next box, you loose almost any information. A hassio restart will recover.

**Comment by KennieNL** [comment] 2020-12-12 17:30
Same here, haven't figured a pattern yet. If i can/need to check anything when it happens, let me know.

**Comment by nljuggler** [comment] 2020-12-18 09:52
I can confirm the behaviour @Polderdijk is describing.

Steps to reproduce:

1. Restart HA (just to make sure the connection is there)
2. Turn on the the Mediabox Next
3. (Use HA to confirm the connection is there)
4. Using the remote, start a previously recorded program
5. Turn off the Mediabox (while playing the recording)
6. Turn the Mediabox on using HA (this still works once)
7. From this point forward the connection is lost.

**Comment by geertsmichael** [comment] 2020-12-20 16:00
I was able to reproduce the issue and a fix is coming.

**Comment by Sholofly** [comment] 2020-12-20 17:59
Should be fixed. Please let me know your findings.

**Comment by X1pheR** [comment] 2020-12-20 18:35
I'm also experiencing the lost connection issue. Good to see a probable fix is here now. Will also report my findings. Love your work BTW. We use the integration A LOT!

**Comment by Sholofly** [comment] 2020-12-20 18:38
Could you update the component. Should be fixed in the latest version.

**Comment by caro7372** [comment] 2020-12-20 18:42
I updated just one minute ago and my daughter is watching a recording.
When she is done I will shutdown the mediabox with HA while playing the recording.
Start up the mediabox again and see what happens.

**Comment by caro7372** [comment] 2020-12-20 19:22
Here we are again.

This is what I did. While playing a recording I did shut down the Ziggobox from within HA.
It did shut down but the 'power' button in HA kept its orange color.
I could not turn on from within HA and when starting the box with its own remote nothing was showed in HA.

Regards,

Robert

**Comment by Sholofly** [comment] 2020-12-20 19:32
Do you have errors in the logging?

Op zo 20 dec. 2020 om 20:22 schreef caro7372 <notifications@github.com>:

**Comment by caro7372** [comment] 2020-12-20 19:35
Where exactly you want me to look. In the supervisor log?
There are no errors.

**Comment by geertsmichael** [comment] 2020-12-20 20:04
The error will be visible in the home assistant log or core log.

**Comment by nljuggler** [comment] 2020-12-21 10:45
> I was able to reproduce the issue and a fix is coming.
> Thanks for the detailed issue description, that is very useful.
> 
> See [Sholofly/ziggonext-python#26](https://github.com/Sholofly/ziggonext-python/pull/26)

That are the quirks of being a software developer. ;-)

**Comment by KennieNL** [comment] 2020-12-23 11:24
I do not see anything in the core log when this issue does happen.

**Comment by Sholofly** [comment] 2020-12-26 08:39
Hi @ashmodai6  & @KennieNL I did a stability update last week. Would you mind to check if the issue still exist?

**Comment by caro7372** [comment] 2020-12-26 08:41
For me it still exists. But I will test it right now.
Comments wil follow underneath this line.
------------------------------------------------------------------------------------------------------------------

**Comment by KennieNL** [comment] 2020-12-30 12:30
Seems stable for me at this point.

**Comment by ashmodai6** [comment] 2021-01-02 13:29
I still have issues in my side without being able to spot what is causing them. From logs I see

media_player.eos_cpe: Sources out of sync. Restart Home Assistant
14:25:59 – HomeKit (WARNING) - message survenu pour la première fois à 26 décembre 2020 à 18:49:44 et apparu 477 fois.

**Comment by steuerzentrale** [comment] 2021-01-17 15:45
First of all many thanks for this component!

I have the same issue, HA is not in sync with my UPC tv box (Switzerland) and it seems to loose the connection after around one day. After updating to the newest version of HA, it does recognize the box, but it doenst update the status. A restart and even reboot HA doesnt seem to help. In the screenshot the media_player entity states playing, but the box is in sleep mode (high energy mode). The control buttons dont work in HA.

infos of my config:
Core core-2021.1.4 
HA OS 5.10
HACS 1.10.0

log attached

I dont have knowledge of coding but would be glad to help with testing or something else which may help.

Many thanks

Andrew

<img width="685" alt="log" src="https://user-images.githubusercontent.com/75168550/104847878-9de7cf00-58e2-11eb-9580-7567e4e8b078.png">
<img width="770" alt="log2" src="https://user-images.githubusercontent.com/75168550/104847881-9fb19280-58e2-11eb-9493-c4d990d56a5b.png">
<img width="398" alt="media_entity" src="https://user-images.githubusercontent.com/75168550/104847882-a04a2900-58e2-11eb-8ee0-c84cd45f86f6.png">

**Comment by geertsmichael** [comment] 2021-01-17 18:33
I put in a fix for CH specific: https://github.com/Sholofly/ziggonext-python/pull/28
@Sholofly can you release a new version of ziggonext-python?

**Comment by Sholofly** [comment] 2021-01-17 20:41
Check, you can update!

Op zo 17 jan. 2021 19:33 schreef Michaël <notifications@github.com>:

**Comment by steuerzentrale** [comment] 2021-01-17 21:12
you guys are fantastic! now its working again ;) I will keep an eye on the box if the connection remains and would inform here if I discover anything unusual.

just a little side note: it takes around 5-10 secs for state changes, e.g from playing to paused. I use the state of the media_player for a light dimming automation, thats why I noticed that.

anyway, many thanks for this cool component.

**Comment by Polderdijk** [comment] 2021-02-09 17:03
Hi,

Sinds a few weeks the component fails again after a while.

I can't remember the exact moment, but got the following error in the log:

`Traceback (most recent call last): File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/usr/local/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main self.loop_forever(retry_first_connection=True) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever rc = self.loop(timeout, max_packets) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop rc = self.loop_read(max_packets) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read rc = self._packet_read() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read rc = self._packet_handle() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle return self._handle_publish() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish self._handle_on_message(message) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message self.on_message(self, self._userdata, message) File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 225, in _on_mqtt_client_message self.settop_boxes[deviceId].update_settop_box(jsonPayload) File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 142, in update_settop_box eventId = stateSource["eventId"] TypeError: 'NoneType' object is not subscriptable`

If you need more info to solve this issue, please let me known!

Thanks for the great work.

P.s. add a 'buy me a beer' button ;-)

**Comment by Polderdijk** [comment] 2021-02-09 17:11
> just a little side note: it takes around 5-10 secs for state changes, e.g from playing to paused. I use the state of the media_player for a light dimming automation, thats why I noticed that.

You can add a template sensor in HA to extract the needed attribute(s) from the main ziggo integration. Then you got (almost) realtime the correct information for your automations.

Like:
`value_template: '{{ state_attr("media_player.ziggo", "play_mode") }}'`

**Comment by Sholofly** [comment] 2021-02-09 17:38
> Hi,
> 
> Sinds a few weeks the component fails again after a while.
> 
> I can't remember the exact moment, but got the following error in the log:
> 
> `Traceback (most recent call last): File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/usr/local/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main self.loop_forever(retry_first_connection=True) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever rc = self.loop(timeout, max_packets) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop rc = self.loop_read(max_packets) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read rc = self._packet_read() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read rc = self._packet_handle() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle return self._handle_publish() File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish self._handle_on_message(message) File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message self.on_message(self, self._userdata, message) File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 225, in _on_mqtt_client_message self.settop_boxes[deviceId].update_settop_box(jsonPayload) File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 142, in update_settop_box eventId = stateSource["eventId"] TypeError: 'NoneType' object is not subscriptable`
> 
> If you need more info to solve this issue, please let me known!
> 
> Thanks for the great work.
> 
> P.s. add a 'buy me a beer' button ;-)

Thanks for the detailed information. It's hard to reproduce but in the end I can work around it and isolate and log the message to find out what's causing this error. I'll look into it this week, and keep you posted.

There's a buy me a coffee link on top of the docs. I'm not into this for the money and my python skills are not very impressive so I didn't want to add too much buttons for payment solutions. I'm afraid I can't live up to the expectations that come with them ;). But anyway: thanks for the hint and the implicit compliment!

**Comment by Sholofly** [comment] 2021-02-09 19:49
@Polderdijk I've updated the component. It will log the state of the box if your error occurs again, but it shouldn't cause the box to become unresponsive. Would you mind to keep an eye on your logs to detect if the error pops up again the coming weeks?

**Comment by Polderdijk** [comment] 2021-02-15 18:54
> 
> 
> @Polderdijk I've updated the component. It will log the state of the box if your error occurs again, but it shouldn't cause the box to become unresponsive. Would you mind to keep an eye on your logs to detect if the error pops up again the coming weeks?

I can confirm that after updating the component now works for over a few days.

Thanks!

**Comment by Sholofly** [comment] 2021-02-20 08:01
Would you keep an eye on the logs? I just used a work around to prevent de box from stopping, but i am curious why it stopped. It gets an update from your mediabox but with a message it couldn't handle.

**Comment by Polderdijk** [comment] 2021-02-25 11:00
I found another reason why the component loose the connection.
When looking on the time, I think the reasen for this is likeley a Next software update, maintanance, connection error or something. The box was off over an hour before this error occours.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 207, in _on_mqtt_client_connect
    client.connect(self._mqtt_broker, DEFAULT_PORT)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1111, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3580, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3623, in _do_handshake
    byte = self._socket.recv(1)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by digital-IMEI** [comment] 2021-03-19 14:48
Hi @Sholofly 

I'm also having this issue where the box becomes unresponsive after a while. As I'm fairly new to Home Assistant I'm not sure if I done everything the right way. Searching for a solution I found this page. 
I replaced the component for the ziggonext-python component (March 9th), expecting more logging. But for some reason that's not happening. The box got stuck yesterday but I can't find any logging... So 2 questions;
- Do i need to use the ZiggoNext or ziggonext-python component? 
- Where do I find the additional logging in HA for you to further investigate? 

Thank you in advance! 

Ivo

**Comment by Sholofly** [comment] 2021-03-21 21:58
Hi Ivo,
You'll need the Ziggo Next component. It uses the python package on the background :)
Please enable debug logging and drop the logs if you have this issue again:

```yaml
logger:
  default: info
  logs:
    custom_components.ziggonext: debug
```

**Comment by digital-IMEI** [comment] 2021-03-25 20:11
Hi @Sholofly ,

Is this the log you need?
`Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:311
First occurred: 9:02:20 PM (1 occurrences) 
Last logged: 9:02:20 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 225, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 142, in update_settop_box
    if not "eventId" in stateSource:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by Sholofly** [comment] 2021-04-01 22:04
Please update to v0.8.2 of this component and please enable debug logging. Should be better now!

**Comment by Sholofly** [comment] 2021-04-08 21:08
Updating to the latest version should fix your issue.

**Closed by Sholofly** 2021-04-08 21:08 UTC

**Comment by bkbartk** [comment] 2021-04-16 17:01
Hello. I like your plugin very much. But I still have this issue ov v0.9.4. 
i use the Dutch ziggo next box. And I have the feeling this issue especially happens after using replaytv/watch back functionality.

**Comment by Sholofly** [comment] 2021-04-16 17:12
@bkbartk Thank you for your message!
I've updated my component a few minutes ago. It should make it more stable. Please update!
Would you mind to help me and enable DEBUG logging for the underlying package in HA? It providers some valuable information about the messages the box communicates with my component.

```yaml
logger:
  default: warning
  logs:
    ziggonext: debug
```

**Comment by bkbartk** [comment] 2021-04-16 18:14
Hello,

Thank you for the update, I applied it. And also added the lines above to my configuration.
I see a lot of additional info in my core log. but since I just needed to restart HA all works fine now.
once stuff stops working I will share the log information.

**Comment by bkbartk** [comment] 2021-04-17 10:05
ok, as promised, here is some log information

> 2021-04-17 07:16:03 DEBUG (Thread-3) [ziggonext.ziggonextbox] Request box state for box Mediabox
2021-04-17 07:16:03 DEBUG (Thread-3) [ziggonext.ziggonext] State update message received: {'version': '1.3.12', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003703073902', 'messageTimeStamp': 1618643763679, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1618607652954, 'source': None}, 'uiState': {}}}
2021-04-17 07:16:03 DEBUG (Thread-3) [ziggonext.ziggonextbox] Updating box 3C36E4-EOSSTB-003703073902 with payload:
2021-04-17 07:16:03 DEBUG (Thread-3) [ziggonext.ziggonextbox] {'version': '1.3.12', 'type': 'CPE.uiStatus', 'source': '3C36E4-EOSSTB-003703073902', 'messageTimeStamp': 1618643763679, 'status': {'uiStatus': 'mainUI', 'playerState': {'sourceType': 'linear', 'speed': 1, 'lastSpeedChangeTime': 1618607652954, 'source': None}, 'uiState': {}}}
2021-04-17 07:16:03 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 238, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 173, in update_settop_box
    if stateSource == "None" or not "channelId" in stateSource:
TypeError: argument of type 'NoneType' is not iterable

at the moment the error ocurred the ziggo box was turned off. and after this one there are no new lines in the log

**Comment by digital-IMEI** [comment] 2021-04-21 19:16
Hi Roelof,
I wanten to share my log with you. Is this the information you are looking for?

`Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:310
First occurred: 8:22:48 PM (1 occurrences) 
Last logged: 8:22:48 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 238, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 173, in update_settop_box
    if stateSource == "None" or not "channelId" in stateSource:
TypeError: argument of type 'NoneType' is not iterable
`

**Comment by digital-IMEI** [comment] 2021-05-03 19:59
Hi Rudolf (sorry I misspelled your name last post! ;) )

any news on this or perhaps should I open a new issue ? I’m still facing the same issues as when going true the steps @nljuggler described. 

See the log above. 

Thanks in advance!

**Comment by bkbartk** [comment] 2021-08-29 19:16
Hello @Sholofly 
Is this issue still in the picture? the status says closed, 
but I still have this issue every now and then.

**Comment by X1pheR** [comment] 2021-09-03 14:32
Me too. It doesn't happen that often as it used to but when it does the only solution is still to restart home assistant. If I can do anything to provide additional info please say so and how 😉

**Comment by ashmodai6** [comment] 2021-09-03 15:10
Indeed still occurs for me as well despite all previous fixes...

**Comment by Sholofly** [comment] 2021-09-03 19:29
Hi @bkbartk, @X1pheR, @digital-IMEI  & @ashmodai6 I have created a new [component](https://github.com/Sholofly/arrisdcx960). Please uninstall the old one and install the new one. It uses a new naming (Arris DCX960) And contains a lot of stability fixes. Please submit a new issue if your issues still exists or if you hav new issues or suggestions. Thank you for your cooperation!

**Comment by X1pheR** [comment] 2021-09-04 22:26
Hi @Sholofly, thanks! I transitioned today to the new component and so far so good. I'll create a new issue if any issues occur. For others it is worth mentioning that besides removing the old component (and its sensor from configuration.yml) you need to at the url of the new component to HACS first because it is not yet known in its own library. So currently you'll only find the old component.

**Comment by Sholofly** [comment] 2021-09-04 22:30
@X1pheR In the meantime the Arris DCX960 repo is added tot te main repo of HACS. So adding a custom repository URLis not longer needed. Some people need to refresh the browser cache after installing the repository in order to see the new integration in the UI.

**Comment by X1pheR** [comment] 2021-09-08 19:33
Excellent. Well still going strong here. No faults so far ;)
