### ISSUE TITLE
Image reloads of program

### ISSUE THREAD

**Issue by silver323** [Sholofly/ZiggoNext#7] opened 2020-01-15 20:07 UTC
Issue with the refreshment of the image of the program that where playing. 
The image is refreshing continuously, maybe it could be the image of the program that is display at the guide of ziggo. 
![image](https://user-images.githubusercontent.com/42837826/72467136-9aef6580-37da-11ea-84fe-1e2989404e78.png)

The issue with the standby mode and the pictures is resolved with the latest version.

**Comment by Sholofly** [comment] 2020-01-15 20:12
Hi @silver323, Thats by design. It's the same image that's used in the Ziggo go app. Maybe you can clarify why you think it's an issue? Is it causing problems?

**Comment by silver323** [comment] 2020-01-15 20:17
No it's not giving problems. I think it's generate more data. I see a huge increase from my database when starting the new component.

**Comment by silver323** [comment] 2020-01-15 20:40
Had found an issue: Changing channel in HA works but the image and title stays on the old channel. 
But when used the Remote changing channel the image and title are changed in HA media player.

**Comment by Sholofly** [comment] 2020-01-16 19:59
I close this one and open a new one about you last issue.

**Closed by Sholofly** 2020-01-16 19:59 UTC
