### ISSUE TITLE
Integration not working after upgrading HA to 0.111.0

### ISSUE THREAD

**Issue by GitHubxtsnl** [Sholofly/ZiggoNext#28] opened 2020-06-11 08:42 UTC
running
HA 0.111.0
HASSOS 4.10
on Pi4

after upgrading to HA 0.110.0 the ziggonext integration reports "The following integrations and platforms could not be set up".

below the snippet of my configuration.yaml.

```
# ZIGGO NEXT MEDIABOX INTEGRATION - ! PLEASE SET ENERGY MODE ON NEXT BOX TO "hoog"
ziggonext:
  username: !secret ziggo_username
  password: !secret ziggo_password
```

**Comment by nelbs** [comment] 2020-06-11 09:14
My log tells me the following:

```
traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/ziggonext/__init__.py", line 30, in setup
    api.initialize(_LOGGER)
  File "/srv/homeassistant/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 124, in initialize
    self.load_channels()
  File "/srv/homeassistant/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 189, in load_channels
    station["images"][2]["url"],
IndexError: list index out of range
```

**Comment by Sjeff** [comment] 2020-06-11 11:09
Same error.

**Comment by golles** [comment] 2020-06-11 13:58
Not sure if that stack trace is accurate (however I got the same). It looks more like it is caused by this: https://github.com/Sholofly/ziggonext-python/blob/master/ziggonext/ziggonext.py#L410

**Comment by Sholofly** [comment] 2020-06-11 14:22
I've got the error too. I Will dive into this tonight!

**Comment by caro7372** [comment] 2020-06-11 15:51
Same here, at first I thought it was caused by the unavailability of the logon to mijnziggo.nl
But that is fixed so I patiently wait.

Regards,

Robert

**Comment by Sholofly** [comment] 2020-06-11 20:00
Resolved in latest version.

**Closed by Sholofly** 2020-06-11 20:00 UTC
Labels: bug

**Comment by Gaijin66-git** [comment] 2020-06-12 10:12
running
HA 0.111.1
HASSOS 4.10
on Pi4 with 4GB

The mediaplayer is working again. Thanks for quick response.
